add blogpost to jdbc to bq template
GoogleCloudPlatform/dataproc-templates pull request #294
Opened 2022-09-15 02:42 UTC by sjlva

Closes #152

2022-09-15 06:36 UTC, shashank-google commented
Thanks @sjlva for the contribution.
@hhasija Is it possible for you to review the blog posts and share your comments if any here.

@sjlva Once reviewed we want this blog post to [GCP Community](https://medium.com/google-cloud).
And publish medium post URL with GCP Community.

2022-09-15 06:37 UTC, shashank-google requested changes

2022-09-15 06:37 UTC, shashank-google commented on README.md
> +* [JDBCToBigQuery](/java/src/main/java/com/google/cloud/dataproc/templates/jdbc/README.md) (blogpost [link](https://medium.com/@sjlva/java-fast-export-large-database-tables-using-gcp-serverless-datap
same changes need to go into /java/README.MD

2022-09-15 06:37 UTC, shashank-google commented on README.md
> +* [JDBCToBigQuery](/python/dataproc_templates/jdbc/README.md) (blogpost [link](https://medium.com/@sjlva/python-fast-export-large-database-tables-using-gcp-serverless-dataproc-bfe77a132485))
same changes need to go into /python/README.MD

2022-09-22 06:53 UTC, shashank-google approved these changes

2022-09-22 06:56 UTC, shashank-google commented
@sjlva 
I just realized your medium posts links are still not show GCP Community.
Have you submitted it ? If not please do so.

2022-09-22 10:39 UTC, hhasija commented
> @sjlva I just realized your medium posts links are still not show GCP Community. Have you submitted it ? If not please do so.



> @sjlva I just realized your medium posts links are still not show GCP Community. Have you submitted it ? If not please do so.

@sjlva Please let me know, in case if you need any help in publishing those blog posts to GCP Community.

2022-09-22 11:10 UTC, sjlva commented
> > @sjlva I just realized your medium posts links are still not show GCP Community. Have you submitted it ? If not please do so.
> 
> > @sjlva I just realized your medium posts links are still not show GCP Community. Have you submitted it ? If not please do so.
> 
> @sjlva Please let me know, in case if you need any help in publishing those blog posts to GCP Community.

@hhasija I asked alexisimp on Twitter. This is the only way to publish those to GCP Community, right?

2022-09-26 08:56 UTC, sjlva commented
> > @sjlva I just realized your medium posts links are still not show GCP Community. Have you submitted it ? If not please do so.
> 
> > @sjlva I just realized your medium posts links are still not show GCP Community. Have you submitted it ? If not please do so.
> 
> @sjlva Please let me know, in case if you need any help in publishing those blog posts to GCP Community.

@hhasija Done. Posts in GCP Community :)

2022-09-26 09:00 UTC, hhasija commented
> > > @sjlva I just realized your medium posts links are still not show GCP Community. Have you submitted it ? If not please do so.
> > 
> > 
> > > @sjlva I just realized your medium posts links are still not show GCP Community. Have you submitted it ? If not please do so.
> > 
> > 
> > @sjlva Please let me know, in case if you need any help in publishing those blog posts to GCP Community.
> 
> @hhasija Done. Posts in GCP Community :)

Looks good @sjlva . If you are done with blog posts and also if you have updated the Read me files as well. Then I would suggest you to merge this pull request, so that corresponding issues would get closed automatically. 

Really thankful for your contributions.

2022-09-26 09:02 UTC, sjlva commented
> > > > @sjlva I just realized your medium posts links are still not show GCP Community. Have you submitted it ? If not please do so.
> > > 
> > > 
> > > > @sjlva I just realized your medium posts links are still not show GCP Community. Have you submitted it ? If not please do so.
> > > 
> > > 
> > > @sjlva Please let me know, in case if you need any help in publishing those blog posts to GCP Community.
> > 
> > 
> > @hhasija Done. Posts in GCP Community :)
> 
> Looks good @sjlva . If you are done with blog posts and also if you have updated the Read me files as well. Then I would suggest you to merge this pull request, so that corresponding issues would get closed automatically.
> 
> Really thankful for your contributions.

@hhasija I do not have permissions to merge.

2022-09-26 09:04 UTC, merged