hive_ddl_extractor.py
GoogleCloudPlatform/dataproc-templates pull request #353
Opened 2022-10-05 13:25 UTC by anuyogamlab

Utility to extract DDLs from hive tables in a DB

2022-10-05 13:26 UTC, anuyogamlab commented
Utility to extract DDLs from Hive tables in a DB.

2022-10-12 18:43 UTC, shashank-google requested changes
Needs to be:
1. Working with Dataproc Serverless. From current code does not looks like, it has been tested.
2. Code quality needs to be in line with other templates, with configurable input and output parameters.
3. Pull request should contain readme updates similar to other templates.

Also I am not sure
What is justification of doing it via `spark` ? 
It seems like as simple for loop to extract ddl for multiple hive tables.
Does it scales to multiple executors for large number of tables ?

2022-10-12 18:43 UTC, shashank-google commented on python/dataproc_templates/util/hive_ddl_extractor.py
> +  ./bin/spark-submit examples/src/main/python/sql/hive.py
where is this ./bin/spark-submit ?

2022-10-12 18:43 UTC, shashank-google commented on python/dataproc_templates/util/hive_ddl_extractor.py
> +        .config("hive.metastore.uris", "thrift://"+host_ip+":9083") \
port hardcoded ?

2022-10-12 18:43 UTC, shashank-google commented on python/dataproc_templates/util/hive_ddl_extractor.py
> +            f = open("hivedumps_{}.ddl".format(db.name), "w")
Why is file being created locally and not on gcs.

2022-10-12 18:43 UTC, shashank-google commented on python/dataproc_templates/util/hive_ddl_extractor.py
> +        ['hadoop fs -copyFromLocal -f hivedumps_'+dbinput+'.ddl hdfs://'+hdfs_path], shell=True)
To be of my knowledge this will fail on dataproc serverless platform as "hadoop" is not available there.

2022-10-12 18:43 UTC, shashank-google commented on python/dataproc_templates/util/hive_ddl_extractor.py
> +            f = open("hivedumps_{}.ddl".format(db.name), "w")
Does it makes sense to have file format should be user configurable like csv / avro  / json  etc.

2022-10-12 18:43 UTC, shashank-google commented on python/dataproc_templates/util/hive_ddl_extractor.py
> +                print("Processing Table: "+db.name+"."+t.name)
logger should be used instead of system outs

2022-12-13 16:33 UTC, surjits254 commented
Closing this as duplicate with #398

2022-12-13 16:33 UTC, closed without merging