Oracle2spanner notebook solution
GoogleCloudPlatform/dataproc-templates pull request #363
Opened 2022-10-14 11:54 UTC by surjits254

This notebook solution migrates data from oracle to spanner. Notebook uses JDBC to Spanner java template.

Closes #224

2022-10-24 21:04 UTC, NiloFreitas requested changes
Nice work @surjits254 !!!

2022-10-24 21:04 UTC, NiloFreitas commented on notebooks/oracle2spanner/OracleToSpanner_notebook.ipynb
> +    "This notebook helps with the step by step process of migrating oracle database tables to cloud spanner using Dataproc template.\n",
Also, add a comment that the migration will create the Spanner tables if not exist, and it will overwrite if executed more then 1 time.

2022-10-25 13:18 UTC, surjits254 commented on notebooks/oracle2spanner/OracleToSpanner_notebook.ipynb
> +    "#### Oracle client Installation"
Done

2022-10-25 13:18 UTC, surjits254 commented on notebooks/oracle2spanner/OracleToSpanner_notebook.ipynb
> +    "cd /opt/oracle\n",
DOne

2022-10-25 13:19 UTC, surjits254 commented on notebooks/oracle2spanner/OracleToSpanner_notebook.ipynb
> +    "- ORACLETABLE_LIST : list of tables you want to migrate eg: ['table1','table2'] else provide an empty list for migration whole database eg : []\n",
Done

2022-10-25 13:19 UTC, surjits254 commented on notebooks/oracle2spanner/OracleToSpanner_notebook.ipynb
> +    "#### copying JARS files to GCS_STAGING_LOCATION"
Done

2022-10-25 13:19 UTC, surjits254 commented on notebooks/oracle2spanner/OracleToSpanner_notebook.ipynb
> +    "Below variables shoulld not be changed unless required\n",
Done

2022-10-25 13:19 UTC, surjits254 commented on notebooks/oracle2spanner/OracleToSpanner_notebook.ipynb
> +    "This notebook helps with the step by step process of migrating oracle database tables to cloud spanner using Dataproc template.\n",
Done

2022-10-25 13:53 UTC, surjits254 commented on notebooks/oracle2spanner/OracleToSpanner_notebook.ipynb
> +    "print(CHECK_PARTITION_COLUMN_LIST)"
Done

2022-10-25 13:55 UTC, NiloFreitas approved these changes

2022-10-25 13:56 UTC, merged