Fix Issue #483
GoogleCloudPlatform/dataproc-templates pull request #486
Opened 2023-01-12 05:44 UTC by AshutoshFreak

Fixed issue #483: Altered 3 links within the README document to reference files in the 'main' branch instead of the 'oracle2bq-notebook' branch

2023-01-20 06:10 UTC, shashank-google requested changes

2023-01-20 06:10 UTC, shashank-google commented on notebooks/oracle2bq/README.md
> +[dataproc-templates/python/notebooks/oracle2bq](https://github.com/GoogleCloudPlatform/dataproc-templates/tree/main/notebooks/oracle2bq) folder and open [OracleToBigQuery_vertex_pipeline_pyspark.ipyn
we should use relative paths when linking to other files of the same repo eg:`[OracleToBigQuery_vertex_pipeline_pyspark.ipynb](/notebooks/oracle2bq/OracleToBigQuery_notebook.ipynb)`

2023-01-27 09:15 UTC, AshutoshFreak commented
I've fixed the relative path issue. I am following the commit conventions, but it doesn't seem to pass the tests. Does the PR name needs to follow the same convention? I'll have to close this PR and open a new one if that's the case

2023-01-30 11:23 UTC, vanshaj-bhatia commented
> 

@AshutoshFreak Please rename the PR using the same conventions.

> @shashank-google I've fixed the relative path issue. I am following the commit conventions, but it doesn't seem to pass the tests. Does the PR name needs to follow the same convention? I'll have to close this PR and open a new one if that's the case

2023-01-31 05:16 UTC, ankuljain09 commented
@AshutoshFreak - You could close the PR and reopen to make the commit-checker bot to run again. Also, please ensure to push a new commit message that looks similar to this-
fix: Updated Readme with correct links

2023-02-03 11:03 UTC, closed without merging