fix: Cassandra templates should accept either query or input table
GoogleCloudPlatform/dataproc-templates pull request #567
Opened 2023-02-02 06:10 UTC by poojabasker20

2023-02-07 08:38 UTC, vanshaj-bhatia requested changes

2023-02-07 12:34 UTC, poojabasker20 commented on java/src/main/java/com/google/cloud/dataproc/templates/databases/CassandraToGCSConfig.java
> +            || (StringUtils.isNotBlank(keyspace) && StringUtils.isNotBlank(inputTable))));
Updated.

2023-02-07 12:35 UTC, poojabasker20 commented on java/src/main/java/com/google/cloud/dataproc/templates/snowflake/SnowflakeToGCSConfig.java
> +                && StringUtils.isNotBlank(sfTable))));
Improved readability by breaking the check in two as done in the python template.

2023-02-07 18:24 UTC, vanshaj-bhatia requested changes

2023-02-07 18:24 UTC, vanshaj-bhatia commented on java/src/main/java/com/google/cloud/dataproc/templates/snowflake/SnowflakeToGCSConfig.java
> +            && StringUtils.isBlank(sfTable)));
This condition doesn't seem correct. Please review.

2023-02-08 05:18 UTC, vanshaj-bhatia approved these changes
LGTM

2023-02-08 05:18 UTC, merged