Blogpost for Hbase to GCS - Python
GoogleCloudPlatform/dataproc-templates pull request #579
Opened 2023-02-10 18:12 UTC by nehamodgil

2023-02-13 17:20 UTC, surjits254 requested changes

2023-02-13 17:20 UTC, surjits254 commented on README.md
> +* [HbaseToGCS](/python/dataproc_templates/hbase#hbase-to-gcs) (blogpost [link](https://medium.com/google-cloud/processing-and-migrating-large-data-tables-from-hive-to-gcs-using-java-and-dataproc-serv
This is hive to GCS, please add correct link

2023-03-14 05:06 UTC, shashank-google commented
@nehamodgil bumping up

2023-03-16 16:22 UTC, shashank-google approved these changes

2023-03-16 16:23 UTC, shashank-google approved these changes

2023-03-16 16:24 UTC, merged