feat: created JDBCToJDBC template
GoogleCloudPlatform/dataproc-templates pull request #669
Opened 2023-03-08 04:48 UTC by poojabasker20

2023-03-09 09:46 UTC, vanshaj-bhatia requested changes

2023-03-09 09:46 UTC, vanshaj-bhatia commented on java/src/main/java/com/google/cloud/dataproc/templates/jdbc/JDBCToJDBC.java
> +      }
Primary key should only be added if no user transformation has been performed.
`inputData = spark.sql(config.getJdbcTempSQLQuery());`

2023-03-09 09:46 UTC, vanshaj-bhatia commented on java/src/main/java/com/google/cloud/dataproc/templates/jdbc/JDBCToJDBC.java
> +    }
Avoid try-catch

2023-03-09 09:46 UTC, vanshaj-bhatia commented
Please update README and java/README files

2023-03-09 15:50 UTC, poojabasker20 commented
> Please update README and java/README files

Updated

2023-03-18 04:03 UTC, hhasija commented on java/src/main/java/com/google/cloud/dataproc/templates/jdbc/README.md
> +--templateProperty jdbctojdbc.output.driver="com.microsoft.sqlserver.jdbc.SQLServerDriver" \
I think so, only one example is sufficient enough to understand.

2023-03-20 06:57 UTC, vanshaj-bhatia requested changes

2023-03-20 06:57 UTC, vanshaj-bhatia commented on CHANGELOG.md
Please remove this file

2023-03-20 06:58 UTC, vanshaj-bhatia commented
@poojabasker20 I can see some changes are not related to this issue. Can you please revert those back?

2023-03-20 10:15 UTC, poojabasker20 commented on CHANGELOG.md
Done

2023-03-20 10:16 UTC, poojabasker20 commented on java/src/main/java/com/google/cloud/dataproc/templates/jdbc/README.md
> +--templateProperty jdbctojdbc.output.driver="com.microsoft.sqlserver.jdbc.SQLServerDriver" \
Updated README with only one example.

2023-03-29 11:45 UTC, vanshaj-bhatia approved these changes
LGTM!

2023-03-29 11:46 UTC, merged