feat: 544 java gcs to mongo template
GoogleCloudPlatform/dataproc-templates pull request #706
Opened 2023-03-21 07:56 UTC by heyanand

Creating pull request to merge changes for new java template gcstomongo

2023-03-21 14:07 UTC, vanshaj-bhatia requested changes

2023-03-21 14:07 UTC, vanshaj-bhatia commented on java/src/main/java/com/google/cloud/dataproc/templates/util/TemplateConstants.java
> -
Please run mvn spotless:apply

2023-03-21 14:07 UTC, vanshaj-bhatia commented on java/src/main/java/com/google/cloud/dataproc/templates/util/TemplateConstants.java
Run `mvn spotless:apply`

2023-03-21 14:07 UTC, vanshaj-bhatia commented on java/src/main/java/com/google/cloud/dataproc/templates/gcs/README.md
> +
Can we add some more info about the connector, probably the hyperlinks to maven repo?

2023-03-21 14:07 UTC, vanshaj-bhatia commented on java/src/main/java/com/google/cloud/dataproc/templates/gcs/GCStoMongo.java
> +      }
Incorrect usage of try-catch. Please remove try-catch.

2023-03-21 14:07 UTC, vanshaj-bhatia commented on java/src/main/java/com/google/cloud/dataproc/templates/gcs/GCStoMongo.java
> +      }
Can this be handled by template.properties file?

2023-03-23 11:18 UTC, heyanand commented on README.md
> +* [TextToBigquery](/java/src/main/java/com/google/cloud/dataproc/templates/gcs#7-text-to-bigquery)
Updated main readme

2023-03-23 11:19 UTC, heyanand commented on java/README.md
> +* [TextToBigquery](/java/src/main/java/com/google/cloud/dataproc/templates/gcs#7-text-to-bigquery)
This is done

2023-03-23 11:20 UTC, heyanand commented on java/src/main/java/com/google/cloud/dataproc/templates/util/TemplateConstants.java
Ran this and the file has been updated.

2023-03-23 11:22 UTC, heyanand commented on java/src/main/resources/template.properties
> +
Updated template.properties to provide default values.

2023-03-30 10:05 UTC, heyanand commented
@vanshaj-bhatia The integration tests are added in the Jenkinsfile and the tests passed without any issues. [Build#45] (https://dataproctemplatesci.com/job/dataproc-templates-build/job/ad-hoc/job/integration-tests-java/45/)

2023-04-03 05:49 UTC, vanshaj-bhatia approved these changes
LGTM

2023-04-03 05:49 UTC, merged